// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/social/v1/social_messages.proto

package social

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FriendRequestStatus - статус заявки в друзья
type FriendRequestStatus int32

const (
	// Не указан
	FriendRequestStatus_FRIEND_REQUEST_STATUS_UNSPECIFIED FriendRequestStatus = 0
	// Ожидает ответа
	FriendRequestStatus_FRIEND_REQUEST_STATUS_PENDING FriendRequestStatus = 1
	// Принята
	FriendRequestStatus_FRIEND_REQUEST_STATUS_ACCEPTED FriendRequestStatus = 2
	// Отклонена
	FriendRequestStatus_FRIEND_REQUEST_STATUS_DECLINED FriendRequestStatus = 3
)

// Enum value maps for FriendRequestStatus.
var (
	FriendRequestStatus_name = map[int32]string{
		0: "FRIEND_REQUEST_STATUS_UNSPECIFIED",
		1: "FRIEND_REQUEST_STATUS_PENDING",
		2: "FRIEND_REQUEST_STATUS_ACCEPTED",
		3: "FRIEND_REQUEST_STATUS_DECLINED",
	}
	FriendRequestStatus_value = map[string]int32{
		"FRIEND_REQUEST_STATUS_UNSPECIFIED": 0,
		"FRIEND_REQUEST_STATUS_PENDING":     1,
		"FRIEND_REQUEST_STATUS_ACCEPTED":    2,
		"FRIEND_REQUEST_STATUS_DECLINED":    3,
	}
)

func (x FriendRequestStatus) Enum() *FriendRequestStatus {
	p := new(FriendRequestStatus)
	*p = x
	return p
}

func (x FriendRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_social_v1_social_messages_proto_enumTypes[0].Descriptor()
}

func (FriendRequestStatus) Type() protoreflect.EnumType {
	return &file_api_social_v1_social_messages_proto_enumTypes[0]
}

func (x FriendRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendRequestStatus.Descriptor instead.
func (FriendRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{0}
}

// SendFriendRequestRequest - запрос на отправку заявки в друзья
type SendFriendRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя, которому отправляется заявка
	UserId        string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SendFriendRequestRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// SendFriendRequestResponse - ответ SendFriendRequest
type SendFriendRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Заявка в друзья
	Request       *FriendRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SendFriendRequestResponse) GetRequest() *FriendRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// ListRequestsRequest - запрос списка заявок в друзья
type ListRequestsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя, для которого получаем заявки
	UserId        string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsRequest) Reset() {
	*x = ListRequestsRequest{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsRequest) ProtoMessage() {}

func (x *ListRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListRequestsRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequestsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListRequestsResponse - ответ списка заявок в друзья
type ListRequestsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список заявок
	Requests      []*FriendRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequestsResponse) Reset() {
	*x = ListRequestsResponse{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequestsResponse) ProtoMessage() {}

func (x *ListRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListRequestsResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequestsResponse) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// AcceptFriendRequestRequest - запрос на принятие заявки в друзья
type AcceptFriendRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id заявки
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestRequest) Reset() {
	*x = AcceptFriendRequestRequest{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRequest) ProtoMessage() {}

func (x *AcceptFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptFriendRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// AcceptFriendRequestResponse - ответ на принятие заявки
type AcceptFriendRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Принятая заявка
	Request       *FriendRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptFriendRequestResponse) Reset() {
	*x = AcceptFriendRequestResponse{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestResponse) ProtoMessage() {}

func (x *AcceptFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptFriendRequestResponse) GetRequest() *FriendRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// DeclineFriendRequestRequest - запрос на отклонение заявки в друзья
type DeclineFriendRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id заявки
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestRequest) Reset() {
	*x = DeclineFriendRequestRequest{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestRequest) ProtoMessage() {}

func (x *DeclineFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DeclineFriendRequestRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// DeclineFriendRequestResponse - ответ на отклонение заявки
type DeclineFriendRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отклонённая заявка
	Request       *FriendRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeclineFriendRequestResponse) Reset() {
	*x = DeclineFriendRequestResponse{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeclineFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineFriendRequestResponse) ProtoMessage() {}

func (x *DeclineFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*DeclineFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{7}
}

func (x *DeclineFriendRequestResponse) GetRequest() *FriendRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

// RemoveFriendRequest - запрос на удаление из друзей
type RemoveFriendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id друга, которого нужно удалить
	UserId        string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendRequest) Reset() {
	*x = RemoveFriendRequest{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRequest) ProtoMessage() {}

func (x *RemoveFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRequest.ProtoReflect.Descriptor instead.
func (*RemoveFriendRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RemoveFriendResponse - ответ на удаление из друзей
type RemoveFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendResponse) Reset() {
	*x = RemoveFriendResponse{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendResponse) ProtoMessage() {}

func (x *RemoveFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendResponse.ProtoReflect.Descriptor instead.
func (*RemoveFriendResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{9}
}

// ListFriendsRequest - запрос списка друзей
type ListFriendsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя
	UserId string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	// Лимит количества друзей
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Курсор для постраничной навигации
	Cursor        string `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ListFriendsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListFriendsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFriendsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// ListFriendsResponse - ответ списка друзей
type ListFriendsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id друзей
	FriendUserIds []string `protobuf:"bytes,1,rep,name=friend_user_ids,proto3" json:"friend_user_ids,omitempty"`
	// Следующий курсор
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ListFriendsResponse) GetFriendUserIds() []string {
	if x != nil {
		return x.FriendUserIds
	}
	return nil
}

func (x *ListFriendsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// FriendRequest - структура заявки в друзья
type FriendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id заявки
	RequestId string `protobuf:"bytes,1,opt,name=request_id,proto3" json:"request_id,omitempty"`
	// Статус заявки
	Status        FriendRequestStatus `protobuf:"varint,2,opt,name=status,proto3,enum=api.social.v1.FriendRequestStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_api_social_v1_social_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_v1_social_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_api_social_v1_social_messages_proto_rawDescGZIP(), []int{12}
}

func (x *FriendRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FriendRequest) GetStatus() FriendRequestStatus {
	if x != nil {
		return x.Status
	}
	return FriendRequestStatus_FRIEND_REQUEST_STATUS_UNSPECIFIED
}

var File_api_social_v1_social_messages_proto protoreflect.FileDescriptor

const file_api_social_v1_social_messages_proto_rawDesc = "" +
	"\n" +
	"#api/social/v1/social_messages.proto\x12\rapi.social.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xbc\x02\n" +
	"\x18SendFriendRequestRequest\x12\xb3\x01\n" +
	"\auser_id\x18\x01 \x01(\tB\x98\x01\x92A\x8a\x01*\auser_id2SId пользователя, которому отправляется заявкаJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\auser_id:j\x92Ag\n" +
	"e*\x18SendFriendRequestRequest2?Запрос на отправку заявки в друзья\xd2\x01\auser_id\"\x93\x01\n" +
	"\x19SendFriendRequestResponse\x126\n" +
	"\arequest\x18\x01 \x01(\v2\x1c.api.social.v1.FriendRequestR\arequest:>\x92A;\n" +
	"9*\x19SendFriendRequestResponse2\x1cОтвет SendFriendRequest\"\xa8\x02\n" +
	"\x13ListRequestsRequest\x12\xb2\x01\n" +
	"\auser_id\x18\x01 \x01(\tB\x97\x01\x92A\x89\x01*\auser_id2RId пользователя, для которого получаем заявкиJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\auser_id:\\\x92AY\n" +
	"W*\x13ListRequestsRequest26Запрос списка заявок в друзья\xd2\x01\auser_id\"\xe1\x01\n" +
	"\x14ListRequestsResponse\x12v\n" +
	"\brequests\x18\x01 \x03(\v2\x1c.api.social.v1.FriendRequestB<\x92A9*\brequests2)Список заявок в друзья\x9a\x02\x01\x01R\brequests:Q\x92AN\n" +
	"L*\x14ListRequestsResponse24Ответ списка заявок в друзья\"\x85\x02\n" +
	"\x1aAcceptFriendRequestRequest\x12v\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tBV\x92AI*\n" +
	"request_id2\x0fId заявкиJ&\"7c9fd952-5c7d-4268-acfb-85563dba1a74\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"request_id:o\x92Al\n" +
	"j*\x1aAcceptFriendRequestRequest2?Запрос на принятие заявки в друзья\xd2\x01\n" +
	"request_id\"\xb8\x01\n" +
	"\x1bAcceptFriendRequestResponse\x126\n" +
	"\arequest\x18\x01 \x01(\v2\x1c.api.social.v1.FriendRequestR\arequest:a\x92A^\n" +
	"\\*\x1bAcceptFriendRequestResponse2=Ответ на принятие заявки в друзья\"\x8b\x02\n" +
	"\x1bDeclineFriendRequestRequest\x12v\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tBV\x92AI*\n" +
	"request_id2\x0fId заявкиJ&\"7c9fd952-5c7d-4268-acfb-85563dba1a74\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\n" +
	"request_id:t\x92Aq\n" +
	"o*\x1bDeclineFriendRequestRequest2CЗапрос на отклонение заявки в друзья\xd2\x01\n" +
	"request_id\"\xbe\x01\n" +
	"\x1cDeclineFriendRequestResponse\x126\n" +
	"\arequest\x18\x01 \x01(\v2\x1c.api.social.v1.FriendRequestR\arequest:f\x92Ac\n" +
	"a*\x1cDeclineFriendRequestResponse2AОтвет на отклонение заявки в друзья\"\xa4\x02\n" +
	"\x13RemoveFriendRequest\x12\x97\x01\n" +
	"\auser_id\x18\x01 \x01(\tB}\x92Ap*\auser_id29Id друга, которого нужно удалитьJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\auser_id:s\x92Ap\n" +
	"n*\x13RemoveFriendRequest2MЗапрос на удаление пользователя из друзей\xd2\x01\auser_id\"\x80\x01\n" +
	"\x14RemoveFriendResponse:h\x92Ae\n" +
	"c*\x14RemoveFriendResponse2KОтвет на удаление пользователя из друзей\"\xd7\x02\n" +
	"\x12ListFriendsRequest\x12y\n" +
	"\auser_id\x18\x01 \x01(\tB_\x92AR*\auser_id2\x1bId пользователяJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\auser_id\x12a\n" +
	"\x05limit\x18\x02 \x01(\x05BK\x92AH*\x05limit27Количество друзей для выборкиJ\x0220\x9a\x02\x01\x03R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor:K\x92AH\n" +
	"F*\x12ListFriendsRequest2&Запрос списка друзей\xd2\x01\auser_id\"\xd5\x02\n" +
	"\x13ListFriendsResponse\x12\xc0\x01\n" +
	"\x0ffriend_user_ids\x18\x01 \x03(\tB\x95\x01\x92A\x91\x01*\x0ffriend_user_ids2(Id друзей пользователяJP[\"123e4567-e89b-12d3-a456-426614174111\", \"123e4567-e89b-12d3-a456-426614174222\"]\x9a\x02\x01\x01R\x0ffriend_user_ids\x12 \n" +
	"\vnext_cursor\x18\x02 \x01(\tR\vnext_cursor:Y\x92AV\n" +
	"T*\x13ListFriendsResponse2=Ответ списка друзей пользователя\"\xb7\x02\n" +
	"\rFriendRequest\x12l\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tBL\x92AI*\n" +
	"request_id2\x0fId заявкиJ&\"7c9fd952-5c7d-4268-acfb-85563dba1a74\"\x9a\x02\x01\aR\n" +
	"request_id\x12q\n" +
	"\x06status\x18\x02 \x01(\x0e2\".api.social.v1.FriendRequestStatusB5\x92A2*\x06status2\x19Статус заявкиJ\t\"PENDING\"\x9a\x02\x01\aR\x06status:E\x92AB\n" +
	"@*\rFriendRequest2/Структура заявки в друзья*\xa7\x01\n" +
	"\x13FriendRequestStatus\x12%\n" +
	"!FRIEND_REQUEST_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dFRIEND_REQUEST_STATUS_PENDING\x10\x01\x12\"\n" +
	"\x1eFRIEND_REQUEST_STATUS_ACCEPTED\x10\x02\x12\"\n" +
	"\x1eFRIEND_REQUEST_STATUS_DECLINED\x10\x03B\x9f\x01\n" +
	"\x11com.api.social.v1B\x13SocialMessagesProtoP\x01Z\x1fsocial/pkg/api/social/v1;social\xa2\x02\x03ASX\xaa\x02\rApi.Social.V1\xca\x02\rApi\\Social\\V1\xe2\x02\x19Api\\Social\\V1\\GPBMetadata\xea\x02\x0fApi::Social::V1b\x06proto3"

var (
	file_api_social_v1_social_messages_proto_rawDescOnce sync.Once
	file_api_social_v1_social_messages_proto_rawDescData []byte
)

func file_api_social_v1_social_messages_proto_rawDescGZIP() []byte {
	file_api_social_v1_social_messages_proto_rawDescOnce.Do(func() {
		file_api_social_v1_social_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_social_v1_social_messages_proto_rawDesc), len(file_api_social_v1_social_messages_proto_rawDesc)))
	})
	return file_api_social_v1_social_messages_proto_rawDescData
}

var file_api_social_v1_social_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_social_v1_social_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_social_v1_social_messages_proto_goTypes = []any{
	(FriendRequestStatus)(0),             // 0: api.social.v1.FriendRequestStatus
	(*SendFriendRequestRequest)(nil),     // 1: api.social.v1.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),    // 2: api.social.v1.SendFriendRequestResponse
	(*ListRequestsRequest)(nil),          // 3: api.social.v1.ListRequestsRequest
	(*ListRequestsResponse)(nil),         // 4: api.social.v1.ListRequestsResponse
	(*AcceptFriendRequestRequest)(nil),   // 5: api.social.v1.AcceptFriendRequestRequest
	(*AcceptFriendRequestResponse)(nil),  // 6: api.social.v1.AcceptFriendRequestResponse
	(*DeclineFriendRequestRequest)(nil),  // 7: api.social.v1.DeclineFriendRequestRequest
	(*DeclineFriendRequestResponse)(nil), // 8: api.social.v1.DeclineFriendRequestResponse
	(*RemoveFriendRequest)(nil),          // 9: api.social.v1.RemoveFriendRequest
	(*RemoveFriendResponse)(nil),         // 10: api.social.v1.RemoveFriendResponse
	(*ListFriendsRequest)(nil),           // 11: api.social.v1.ListFriendsRequest
	(*ListFriendsResponse)(nil),          // 12: api.social.v1.ListFriendsResponse
	(*FriendRequest)(nil),                // 13: api.social.v1.FriendRequest
}
var file_api_social_v1_social_messages_proto_depIdxs = []int32{
	13, // 0: api.social.v1.SendFriendRequestResponse.request:type_name -> api.social.v1.FriendRequest
	13, // 1: api.social.v1.ListRequestsResponse.requests:type_name -> api.social.v1.FriendRequest
	13, // 2: api.social.v1.AcceptFriendRequestResponse.request:type_name -> api.social.v1.FriendRequest
	13, // 3: api.social.v1.DeclineFriendRequestResponse.request:type_name -> api.social.v1.FriendRequest
	0,  // 4: api.social.v1.FriendRequest.status:type_name -> api.social.v1.FriendRequestStatus
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_social_v1_social_messages_proto_init() }
func file_api_social_v1_social_messages_proto_init() {
	if File_api_social_v1_social_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_v1_social_messages_proto_rawDesc), len(file_api_social_v1_social_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_social_v1_social_messages_proto_goTypes,
		DependencyIndexes: file_api_social_v1_social_messages_proto_depIdxs,
		EnumInfos:         file_api_social_v1_social_messages_proto_enumTypes,
		MessageInfos:      file_api_social_v1_social_messages_proto_msgTypes,
	}.Build()
	File_api_social_v1_social_messages_proto = out.File
	file_api_social_v1_social_messages_proto_goTypes = nil
	file_api_social_v1_social_messages_proto_depIdxs = nil
}
