// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/social/v1/social_service.proto

package social

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_social_v1_social_service_proto protoreflect.FileDescriptor

const file_api_social_v1_social_service_proto_rawDesc = "" +
	"\n" +
	"\"api/social/v1/social_service.proto\x12\rapi.social.v1\x1a#api/social/v1/social_messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xe7\x06\n" +
	"\rSocialService\x12\x87\x01\n" +
	"\x11SendFriendRequest\x12'.api.social.v1.SendFriendRequestRequest\x1a(.api.social.v1.SendFriendRequestResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/friends/requests\x12\x84\x01\n" +
	"\fListRequests\x12\".api.social.v1.ListRequestsRequest\x1a#.api.social.v1.ListRequestsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v1/users/{user_id}/friend-requests\x12\x9e\x01\n" +
	"\x13AcceptFriendRequest\x12).api.social.v1.AcceptFriendRequestRequest\x1a*.api.social.v1.AcceptFriendRequestResponse\"0\x82\xd3\xe4\x93\x02*\"(/v1/friends/requests/{request_id}/accept\x12\xa2\x01\n" +
	"\x14DeclineFriendRequest\x12*.api.social.v1.DeclineFriendRequestRequest\x1a+.api.social.v1.DeclineFriendRequestResponse\"1\x82\xd3\xe4\x93\x02+\")/v1/friends/requests/{request_id}/decline\x12\x83\x01\n" +
	"\fRemoveFriend\x12\".api.social.v1.RemoveFriendRequest\x1a#.api.social.v1.RemoveFriendResponse\"*\x82\xd3\xe4\x93\x02$\"\"/v1/users/{user_id}/friends/remove\x12y\n" +
	"\vListFriends\x12!.api.social.v1.ListFriendsRequest\x1a\".api.social.v1.ListFriendsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/users/{user_id}/friendsB\xe1\x01\x92A@\x12\x16\n" +
	"\rSocialService2\x050.0.1*\x02\x01\x022\x10application/json:\x10application/json\n" +
	"\x11com.api.social.v1B\x12SocialServiceProtoP\x01Z\x1fsocial/pkg/api/social/v1;social\xa2\x02\x03ASX\xaa\x02\rApi.Social.V1\xca\x02\rApi\\Social\\V1\xe2\x02\x19Api\\Social\\V1\\GPBMetadata\xea\x02\x0fApi::Social::V1b\x06proto3"

var file_api_social_v1_social_service_proto_goTypes = []any{
	(*SendFriendRequestRequest)(nil),     // 0: api.social.v1.SendFriendRequestRequest
	(*ListRequestsRequest)(nil),          // 1: api.social.v1.ListRequestsRequest
	(*AcceptFriendRequestRequest)(nil),   // 2: api.social.v1.AcceptFriendRequestRequest
	(*DeclineFriendRequestRequest)(nil),  // 3: api.social.v1.DeclineFriendRequestRequest
	(*RemoveFriendRequest)(nil),          // 4: api.social.v1.RemoveFriendRequest
	(*ListFriendsRequest)(nil),           // 5: api.social.v1.ListFriendsRequest
	(*SendFriendRequestResponse)(nil),    // 6: api.social.v1.SendFriendRequestResponse
	(*ListRequestsResponse)(nil),         // 7: api.social.v1.ListRequestsResponse
	(*AcceptFriendRequestResponse)(nil),  // 8: api.social.v1.AcceptFriendRequestResponse
	(*DeclineFriendRequestResponse)(nil), // 9: api.social.v1.DeclineFriendRequestResponse
	(*RemoveFriendResponse)(nil),         // 10: api.social.v1.RemoveFriendResponse
	(*ListFriendsResponse)(nil),          // 11: api.social.v1.ListFriendsResponse
}
var file_api_social_v1_social_service_proto_depIdxs = []int32{
	0,  // 0: api.social.v1.SocialService.SendFriendRequest:input_type -> api.social.v1.SendFriendRequestRequest
	1,  // 1: api.social.v1.SocialService.ListRequests:input_type -> api.social.v1.ListRequestsRequest
	2,  // 2: api.social.v1.SocialService.AcceptFriendRequest:input_type -> api.social.v1.AcceptFriendRequestRequest
	3,  // 3: api.social.v1.SocialService.DeclineFriendRequest:input_type -> api.social.v1.DeclineFriendRequestRequest
	4,  // 4: api.social.v1.SocialService.RemoveFriend:input_type -> api.social.v1.RemoveFriendRequest
	5,  // 5: api.social.v1.SocialService.ListFriends:input_type -> api.social.v1.ListFriendsRequest
	6,  // 6: api.social.v1.SocialService.SendFriendRequest:output_type -> api.social.v1.SendFriendRequestResponse
	7,  // 7: api.social.v1.SocialService.ListRequests:output_type -> api.social.v1.ListRequestsResponse
	8,  // 8: api.social.v1.SocialService.AcceptFriendRequest:output_type -> api.social.v1.AcceptFriendRequestResponse
	9,  // 9: api.social.v1.SocialService.DeclineFriendRequest:output_type -> api.social.v1.DeclineFriendRequestResponse
	10, // 10: api.social.v1.SocialService.RemoveFriend:output_type -> api.social.v1.RemoveFriendResponse
	11, // 11: api.social.v1.SocialService.ListFriends:output_type -> api.social.v1.ListFriendsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_social_v1_social_service_proto_init() }
func file_api_social_v1_social_service_proto_init() {
	if File_api_social_v1_social_service_proto != nil {
		return
	}
	file_api_social_v1_social_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_v1_social_service_proto_rawDesc), len(file_api_social_v1_social_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_social_v1_social_service_proto_goTypes,
		DependencyIndexes: file_api_social_v1_social_service_proto_depIdxs,
	}.Build()
	File_api_social_v1_social_service_proto = out.File
	file_api_social_v1_social_service_proto_goTypes = nil
	file_api_social_v1_social_service_proto_depIdxs = nil
}
