// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/chat/v1/chat_service.proto

package chat

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_chat_v1_chat_service_proto protoreflect.FileDescriptor

const file_api_chat_v1_chat_service_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/chat/v1/chat_service.proto\x12\vapi.chat.v1\x1a\x1fapi/chat/v1/chat_messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x81\a\n" +
	"\vChatService\x12|\n" +
	"\x10CreateDirectChat\x12$.api.chat.v1.CreateDirectChatRequest\x1a%.api.chat.v1.CreateDirectChatResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/chats/direct\x12a\n" +
	"\aGetChat\x12\x1b.api.chat.v1.GetChatRequest\x1a\x1c.api.chat.v1.GetChatResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/chats/{chat_id}\x12y\n" +
	"\rListUserChats\x12!.api.chat.v1.ListUserChatsRequest\x1a\".api.chat.v1.ListUserChatsResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/users/{user_id}/chats\x12\x81\x01\n" +
	"\x0fListChatMembers\x12#.api.chat.v1.ListChatMembersRequest\x1a$.api.chat.v1.ListChatMembersResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/chats/{chat_id}/members\x12y\n" +
	"\vSendMessage\x12\x1f.api.chat.v1.SendMessageRequest\x1a .api.chat.v1.SendMessageResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/chats/{chat_id}/messages\x12y\n" +
	"\fListMessages\x12 .api.chat.v1.ListMessagesRequest\x1a!.api.chat.v1.ListMessagesResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/chats/{chat_id}/messages\x12\x9b\x01\n" +
	"\x0eStreamMessages\x12\".api.chat.v1.StreamMessagesRequest\x1a#.api.chat.v1.StreamMessagesResponse\">\x92A;\x12\x16Not available via REST\x1a\x1fThis method uses gRPC streamingX\x010\x01B\xcd\x01\x92A>\x12\x14\n" +
	"\vChatService2\x050.0.1*\x02\x01\x022\x10application/json:\x10application/json\n" +
	"\x0fcom.api.chat.v1B\x10ChatServiceProtoP\x01Z\x19chat/pkg/api/chat/v1;chat\xa2\x02\x03ACX\xaa\x02\vApi.Chat.V1\xca\x02\vApi\\Chat\\V1\xe2\x02\x17Api\\Chat\\V1\\GPBMetadata\xea\x02\rApi::Chat::V1b\x06proto3"

var file_api_chat_v1_chat_service_proto_goTypes = []any{
	(*CreateDirectChatRequest)(nil),  // 0: api.chat.v1.CreateDirectChatRequest
	(*GetChatRequest)(nil),           // 1: api.chat.v1.GetChatRequest
	(*ListUserChatsRequest)(nil),     // 2: api.chat.v1.ListUserChatsRequest
	(*ListChatMembersRequest)(nil),   // 3: api.chat.v1.ListChatMembersRequest
	(*SendMessageRequest)(nil),       // 4: api.chat.v1.SendMessageRequest
	(*ListMessagesRequest)(nil),      // 5: api.chat.v1.ListMessagesRequest
	(*StreamMessagesRequest)(nil),    // 6: api.chat.v1.StreamMessagesRequest
	(*CreateDirectChatResponse)(nil), // 7: api.chat.v1.CreateDirectChatResponse
	(*GetChatResponse)(nil),          // 8: api.chat.v1.GetChatResponse
	(*ListUserChatsResponse)(nil),    // 9: api.chat.v1.ListUserChatsResponse
	(*ListChatMembersResponse)(nil),  // 10: api.chat.v1.ListChatMembersResponse
	(*SendMessageResponse)(nil),      // 11: api.chat.v1.SendMessageResponse
	(*ListMessagesResponse)(nil),     // 12: api.chat.v1.ListMessagesResponse
	(*StreamMessagesResponse)(nil),   // 13: api.chat.v1.StreamMessagesResponse
}
var file_api_chat_v1_chat_service_proto_depIdxs = []int32{
	0,  // 0: api.chat.v1.ChatService.CreateDirectChat:input_type -> api.chat.v1.CreateDirectChatRequest
	1,  // 1: api.chat.v1.ChatService.GetChat:input_type -> api.chat.v1.GetChatRequest
	2,  // 2: api.chat.v1.ChatService.ListUserChats:input_type -> api.chat.v1.ListUserChatsRequest
	3,  // 3: api.chat.v1.ChatService.ListChatMembers:input_type -> api.chat.v1.ListChatMembersRequest
	4,  // 4: api.chat.v1.ChatService.SendMessage:input_type -> api.chat.v1.SendMessageRequest
	5,  // 5: api.chat.v1.ChatService.ListMessages:input_type -> api.chat.v1.ListMessagesRequest
	6,  // 6: api.chat.v1.ChatService.StreamMessages:input_type -> api.chat.v1.StreamMessagesRequest
	7,  // 7: api.chat.v1.ChatService.CreateDirectChat:output_type -> api.chat.v1.CreateDirectChatResponse
	8,  // 8: api.chat.v1.ChatService.GetChat:output_type -> api.chat.v1.GetChatResponse
	9,  // 9: api.chat.v1.ChatService.ListUserChats:output_type -> api.chat.v1.ListUserChatsResponse
	10, // 10: api.chat.v1.ChatService.ListChatMembers:output_type -> api.chat.v1.ListChatMembersResponse
	11, // 11: api.chat.v1.ChatService.SendMessage:output_type -> api.chat.v1.SendMessageResponse
	12, // 12: api.chat.v1.ChatService.ListMessages:output_type -> api.chat.v1.ListMessagesResponse
	13, // 13: api.chat.v1.ChatService.StreamMessages:output_type -> api.chat.v1.StreamMessagesResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_chat_v1_chat_service_proto_init() }
func file_api_chat_v1_chat_service_proto_init() {
	if File_api_chat_v1_chat_service_proto != nil {
		return
	}
	file_api_chat_v1_chat_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_chat_service_proto_rawDesc), len(file_api_chat_v1_chat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_v1_chat_service_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_chat_service_proto_depIdxs,
	}.Build()
	File_api_chat_v1_chat_service_proto = out.File
	file_api_chat_v1_chat_service_proto_goTypes = nil
	file_api_chat_v1_chat_service_proto_depIdxs = nil
}
