// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/chat/v1/chat_messages.proto

package chat

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateDirectChatRequest - запрос на создание личного чата
type CreateDirectChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id собеседника
	ParticipantId string `protobuf:"bytes,1,opt,name=participant_id,proto3" json:"participant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatRequest) Reset() {
	*x = CreateDirectChatRequest{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatRequest) ProtoMessage() {}

func (x *CreateDirectChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatRequest.ProtoReflect.Descriptor instead.
func (*CreateDirectChatRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDirectChatRequest) GetParticipantId() string {
	if x != nil {
		return x.ParticipantId
	}
	return ""
}

// CreateDirectChatResponse - ответ на создание чата
type CreateDirectChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id созданного чата
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDirectChatResponse) Reset() {
	*x = CreateDirectChatResponse{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDirectChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDirectChatResponse) ProtoMessage() {}

func (x *CreateDirectChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDirectChatResponse.ProtoReflect.Descriptor instead.
func (*CreateDirectChatResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDirectChatResponse) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// GetChatRequest - запрос получения чата
type GetChatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id чата
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GetChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// GetChatResponse - ответ получения чата
type GetChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Данные чата
	Chat          *Chat `protobuf:"bytes,1,opt,name=chat,proto3" json:"chat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatResponse) Reset() {
	*x = GetChatResponse{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatResponse) ProtoMessage() {}

func (x *GetChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatResponse.ProtoReflect.Descriptor instead.
func (*GetChatResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GetChatResponse) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

// ListUserChatsRequest - запрос списка чатов пользователя
type ListUserChatsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя
	UserId        string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsRequest) Reset() {
	*x = ListUserChatsRequest{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsRequest) ProtoMessage() {}

func (x *ListUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsRequest.ProtoReflect.Descriptor instead.
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{4}
}

func (x *ListUserChatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// ListUserChatsResponse - ответ списка чатов пользователя
type ListUserChatsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список чатов пользователя
	Chats         []*Chat `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserChatsResponse) Reset() {
	*x = ListUserChatsResponse{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserChatsResponse) ProtoMessage() {}

func (x *ListUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserChatsResponse.ProtoReflect.Descriptor instead.
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ListUserChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

// ListChatMembersRequest - запрос списка участников чата
type ListChatMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id чата
	ChatId        string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersRequest) Reset() {
	*x = ListChatMembersRequest{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersRequest) ProtoMessage() {}

func (x *ListChatMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersRequest.ProtoReflect.Descriptor instead.
func (*ListChatMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ListChatMembersRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// ListChatMembersResponse - ответ списка участников чата
type ListChatMembersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список Id участников
	UserIds       []string `protobuf:"bytes,1,rep,name=user_ids,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatMembersResponse) Reset() {
	*x = ListChatMembersResponse{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatMembersResponse) ProtoMessage() {}

func (x *ListChatMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatMembersResponse.ProtoReflect.Descriptor instead.
func (*ListChatMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ListChatMembersResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// SendMessageRequest - запрос на отправку сообщения
type SendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id чата
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	// Текст сообщения
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// SendMessageResponse - ответ на отправку сообщения
type SendMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отправленное сообщение
	Message       *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// ListMessagesRequest - запрос списка сообщений
type ListMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id чата
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	// Количество сообщений
	Limit uint32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Время отправления последнего сообщения в списке (курсор)
	LastMessageTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_message_time,proto3" json:"last_message_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ListMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ListMessagesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetLastMessageTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageTime
	}
	return nil
}

// ListMessagesResponse - ответ списка сообщений
type ListMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список сообщений
	Messages []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	// Следующее время отправления последнего сообщения в списке (курсор)
	LastMessageTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_message_time,proto3" json:"last_message_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{11}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetLastMessageTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageTime
	}
	return nil
}

// StreamMessagesRequest - запрос на поток сообщений
type StreamMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id чата
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	// Время отправления последнего сообщения
	SinceMessageTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since_message_time,proto3" json:"since_message_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{12}
}

func (x *StreamMessagesRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *StreamMessagesRequest) GetSinceMessageTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SinceMessageTime
	}
	return nil
}

// StreamMessagesResponse - ответ потока сообщений
type StreamMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Новое сообщение
	Message       *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessagesResponse) Reset() {
	*x = StreamMessagesResponse{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesResponse) ProtoMessage() {}

func (x *StreamMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesResponse.ProtoReflect.Descriptor instead.
func (*StreamMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{13}
}

func (x *StreamMessagesResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

// Chat - структура чата
type Chat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id чата
	ChatId string `protobuf:"bytes,1,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	// Id участников
	ParticipantIds []string `protobuf:"bytes,2,rep,name=participant_ids,proto3" json:"participant_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{14}
}

func (x *Chat) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Chat) GetParticipantIds() []string {
	if x != nil {
		return x.ParticipantIds
	}
	return nil
}

// Message - структура сообщения
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id сообщения
	MessageId string `protobuf:"bytes,1,opt,name=message_id,proto3" json:"message_id,omitempty"`
	// Id чата
	ChatId string `protobuf:"bytes,2,opt,name=chat_id,proto3" json:"chat_id,omitempty"`
	// Id отправителя
	SenderId string `protobuf:"bytes,3,opt,name=sender_id,proto3" json:"sender_id,omitempty"`
	// Текст сообщения
	Text string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// Время создания сообщения
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_chat_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_chat_messages_proto_rawDescGZIP(), []int{15}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Message) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_chat_v1_chat_messages_proto protoreflect.FileDescriptor

const file_api_chat_v1_chat_messages_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/chat/v1/chat_messages.proto\x12\vapi.chat.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x96\x02\n" +
	"\x17CreateDirectChatRequest\x12\x8d\x01\n" +
	"\x0eparticipant_id\x18\x01 \x01(\tBe\x92AW*\x0eparticipant_id2\x19Id собеседникаJ&\"123e4567-e89b-12d3-a456-426614174001\"\x9a\x02\x01\a\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\x0eparticipant_id:k\x92Ah\n" +
	"f*\x17CreateDirectChatRequest2:Запрос на создание личного чата\xd2\x01\x0eparticipant_id\"\xdc\x01\n" +
	"\x18CreateDirectChatResponse\x12t\n" +
	"\achat_id\x18\x01 \x01(\tBZ\x92AW*\achat_id2 Id созданного чатаJ&\"987e6543-e21b-12d3-a456-426614174999\"\x9a\x02\x01\aR\achat_id:J\x92AG\n" +
	"E*\x18CreateDirectChatResponse2)Ответ на создание чата\"\xcc\x01\n" +
	"\x0eGetChatRequest\x12j\n" +
	"\achat_id\x18\x01 \x01(\tBP\x92AB*\achat_id2\vId чатаJ&\"987e6543-e21b-12d3-a456-426614174999\"\x9a\x02\x01\a\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\achat_id:N\x92AK\n" +
	"I*\x0eGetChatRequest2-Запрос на получение чата\xd2\x01\achat_id\"\x9e\x01\n" +
	"\x0fGetChatResponse\x12K\n" +
	"\x04chat\x18\x01 \x01(\v2\x11.api.chat.v1.ChatB$\x92A!*\x04chat2\x15Данные чата\x9a\x02\x01\x06R\x04chat:>\x92A;\n" +
	"9*\x0fGetChatResponse2&Ответ получения чата\"\xf8\x01\n" +
	"\x14ListUserChatsRequest\x12z\n" +
	"\auser_id\x18\x01 \x01(\tB`\x92AR*\auser_id2\x1bId пользователяJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\a\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\auser_id:d\x92Aa\n" +
	"_*\x14ListUserChatsRequest2=Запрос списка чатов пользователя\xd2\x01\auser_id\"\xdd\x01\n" +
	"\x15ListUserChatsResponse\x12i\n" +
	"\x05chats\x18\x01 \x03(\v2\x11.api.chat.v1.ChatB@\x92A=*\x05chats20Список чатов пользователя\x9a\x02\x01\x01R\x05chats:Y\x92AV\n" +
	"T*\x15ListUserChatsResponse2;Ответ списка чатов пользователя\"\xe6\x01\n" +
	"\x16ListChatMembersRequest\x12j\n" +
	"\achat_id\x18\x01 \x01(\tBP\x92AB*\achat_id2\vId чатаJ&\"987e6543-e21b-12d3-a456-426614174999\"\x9a\x02\x01\a\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\achat_id:`\x92A]\n" +
	"[*\x16ListChatMembersRequest27Запрос списка участников чата\xd2\x01\achat_id\"\xa3\x02\n" +
	"\x17ListChatMembersResponse\x12\xb0\x01\n" +
	"\buser_ids\x18\x01 \x03(\tB\x93\x01\x92A\x8f\x01*\buser_ids2-Список Id участников чатаJP[\"123e4567-e89b-12d3-a456-426614174000\", \"223e4567-e89b-12d3-a456-426614174001\"]\x9a\x02\x01\x01R\buser_ids:U\x92AR\n" +
	"P*\x17ListChatMembersResponse25Ответ списка участников чата\"\xc0\x02\n" +
	"\x12SendMessageRequest\x12j\n" +
	"\achat_id\x18\x01 \x01(\tBP\x92AB*\achat_id2\vId чатаJ&\"987e6543-e21b-12d3-a456-426614174999\"\x9a\x02\x01\a\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\achat_id\x12[\n" +
	"\x04text\x18\x02 \x01(\tBG\x92A:*\x04text2\x1dТекст сообщенияJ\x0f\"Привет!\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\x04text:a\x92A^\n" +
	"\\*\x12SendMessageRequest25Запрос на отправку сообщения\xd2\x01\achat_id\xd2\x01\x04text\"\xd5\x01\n" +
	"\x13SendMessageResponse\x12m\n" +
	"\amessage\x18\x01 \x01(\v2\x14.api.chat.v1.MessageB=\x92A:*\amessage2+Отправленное сообщение\x9a\x02\x01\x06R\amessage:O\x92AL\n" +
	"J*\x13SendMessageResponse23Ответ на отправку сообщения\"\x94\x04\n" +
	"\x13ListMessagesRequest\x12j\n" +
	"\achat_id\x18\x01 \x01(\tBP\x92AB*\achat_id2\vId чатаJ&\"987e6543-e21b-12d3-a456-426614174999\"\x9a\x02\x01\a\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\achat_id\x12g\n" +
	"\x05limit\x18\x02 \x01(\rBQ\x92AN*\x05limit2=Количество сообщений для выборкиJ\x0250\x9a\x02\x01\x03R\x05limit\x12\xd3\x01\n" +
	"\x11last_message_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x88\x01\x92A\x81\x01*\x11last_message_time2hВремя отправления последнего сообщения в списке (курсор)\x9a\x02\x01\a\xe0A\x01R\x11last_message_time:R\x92AO\n" +
	"M*\x13ListMessagesRequest2,Запрос списка сообщений\xd2\x01\achat_id\"\xae\x03\n" +
	"\x14ListMessagesResponse\x12d\n" +
	"\bmessages\x18\x01 \x03(\v2\x14.api.chat.v1.MessageB2\x92A/*\bmessages2\x1fСписок сообщений\x9a\x02\x01\x01R\bmessages\x12\xe6\x01\n" +
	"\x11last_message_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x9b\x01\x92A\x94\x01*\x11last_message_time2{Следующее время отправления последнего сообщения в списке (курсор)\x9a\x02\x01\a\xe0A\x01R\x11last_message_time:G\x92AD\n" +
	"B*\x14ListMessagesResponse2*Ответ списка сообщений\"\xa9\x03\n" +
	"\x15StreamMessagesRequest\x12j\n" +
	"\achat_id\x18\x01 \x01(\tBP\x92AB*\achat_id2\vId чатаJ&\"987e6543-e21b-12d3-a456-426614174999\"\x9a\x02\x01\a\xe0A\x02\xbaH\x05r\x03\xb0\x01\x01R\achat_id\x12\xb5\x01\n" +
	"\x12since_message_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampBi\x92Ac*\x12since_message_time2IВремя отправления последнего сообщения\x9a\x02\x01\a\xe0A\x01R\x12since_message_time:l\x92Ai\n" +
	"g*\x15StreamMessagesRequest2DЗапрос на получение потока сообщений\xd2\x01\achat_id\"\xc4\x01\n" +
	"\x16StreamMessagesResponse\x12_\n" +
	"\amessage\x18\x01 \x01(\v2\x14.api.chat.v1.MessageB/\x92A,*\amessage2\x1dНовое сообщение\x9a\x02\x01\x06R\amessage:I\x92AF\n" +
	"D*\x16StreamMessagesResponse2*Ответ потока сообщений\"\xcc\x02\n" +
	"\x04Chat\x12_\n" +
	"\achat_id\x18\x01 \x01(\tBE\x92AB*\achat_id2\vId чатаJ&\"987e6543-e21b-12d3-a456-426614174999\"\x9a\x02\x01\aR\achat_id\x12\xb8\x01\n" +
	"\x0fparticipant_ids\x18\x02 \x03(\tB\x8d\x01\x92A\x89\x01*\x0fparticipant_ids2 Id участников чатаJP[\"123e4567-e89b-12d3-a456-426614174000\", \"223e4567-e89b-12d3-a456-426614174001\"]\x9a\x02\x01\x01R\x0fparticipant_ids:(\x92A%\n" +
	"#*\x04Chat2\x1bСтруктура чата\"\xd4\x05\n" +
	"\aMessage\x12a\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tBA\x92A>*\n" +
	"message_id2\x15Id сообщенияJ\x15\"abc123-message-uuid\"\x9a\x02\x01\aR\n" +
	"message_id\x12\x9b\x01\n" +
	"\achat_id\x18\x02 \x01(\tB\x80\x01\x92A}*\achat_id2FId чата, к которому относится сообщениеJ&\"987e6543-e21b-12d3-a456-426614174999\"\x9a\x02\x01\aR\achat_id\x12\xa4\x01\n" +
	"\tsender_id\x18\x03 \x01(\tB\x85\x01\x92A\x81\x01*\tsender_id2HId пользователя, отправившего сообщениеJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\aR\tsender_id\x12Y\n" +
	"\x04text\x18\x04 \x01(\tBE\x92AB*\x04text2\x1dТекст сообщенияJ\x17\"Привет, мир!\"\x9a\x02\x01\aR\x04text\x12\x8e\x01\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampBR\x92AO*\n" +
	"created_at2=Метка времени создания сообщения\x9a\x02\x01\aR\n" +
	"created_at:5\x92A2\n" +
	"0*\aMessage2%Структура сообщенияB\x8d\x01\n" +
	"\x0fcom.api.chat.v1B\x11ChatMessagesProtoP\x01Z\x19chat/pkg/api/chat/v1;chat\xa2\x02\x03ACX\xaa\x02\vApi.Chat.V1\xca\x02\vApi\\Chat\\V1\xe2\x02\x17Api\\Chat\\V1\\GPBMetadata\xea\x02\rApi::Chat::V1b\x06proto3"

var (
	file_api_chat_v1_chat_messages_proto_rawDescOnce sync.Once
	file_api_chat_v1_chat_messages_proto_rawDescData []byte
)

func file_api_chat_v1_chat_messages_proto_rawDescGZIP() []byte {
	file_api_chat_v1_chat_messages_proto_rawDescOnce.Do(func() {
		file_api_chat_v1_chat_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_v1_chat_messages_proto_rawDesc), len(file_api_chat_v1_chat_messages_proto_rawDesc)))
	})
	return file_api_chat_v1_chat_messages_proto_rawDescData
}

var file_api_chat_v1_chat_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_chat_v1_chat_messages_proto_goTypes = []any{
	(*CreateDirectChatRequest)(nil),  // 0: api.chat.v1.CreateDirectChatRequest
	(*CreateDirectChatResponse)(nil), // 1: api.chat.v1.CreateDirectChatResponse
	(*GetChatRequest)(nil),           // 2: api.chat.v1.GetChatRequest
	(*GetChatResponse)(nil),          // 3: api.chat.v1.GetChatResponse
	(*ListUserChatsRequest)(nil),     // 4: api.chat.v1.ListUserChatsRequest
	(*ListUserChatsResponse)(nil),    // 5: api.chat.v1.ListUserChatsResponse
	(*ListChatMembersRequest)(nil),   // 6: api.chat.v1.ListChatMembersRequest
	(*ListChatMembersResponse)(nil),  // 7: api.chat.v1.ListChatMembersResponse
	(*SendMessageRequest)(nil),       // 8: api.chat.v1.SendMessageRequest
	(*SendMessageResponse)(nil),      // 9: api.chat.v1.SendMessageResponse
	(*ListMessagesRequest)(nil),      // 10: api.chat.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),     // 11: api.chat.v1.ListMessagesResponse
	(*StreamMessagesRequest)(nil),    // 12: api.chat.v1.StreamMessagesRequest
	(*StreamMessagesResponse)(nil),   // 13: api.chat.v1.StreamMessagesResponse
	(*Chat)(nil),                     // 14: api.chat.v1.Chat
	(*Message)(nil),                  // 15: api.chat.v1.Message
	(*timestamppb.Timestamp)(nil),    // 16: google.protobuf.Timestamp
}
var file_api_chat_v1_chat_messages_proto_depIdxs = []int32{
	14, // 0: api.chat.v1.GetChatResponse.chat:type_name -> api.chat.v1.Chat
	14, // 1: api.chat.v1.ListUserChatsResponse.chats:type_name -> api.chat.v1.Chat
	15, // 2: api.chat.v1.SendMessageResponse.message:type_name -> api.chat.v1.Message
	16, // 3: api.chat.v1.ListMessagesRequest.last_message_time:type_name -> google.protobuf.Timestamp
	15, // 4: api.chat.v1.ListMessagesResponse.messages:type_name -> api.chat.v1.Message
	16, // 5: api.chat.v1.ListMessagesResponse.last_message_time:type_name -> google.protobuf.Timestamp
	16, // 6: api.chat.v1.StreamMessagesRequest.since_message_time:type_name -> google.protobuf.Timestamp
	15, // 7: api.chat.v1.StreamMessagesResponse.message:type_name -> api.chat.v1.Message
	16, // 8: api.chat.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_chat_v1_chat_messages_proto_init() }
func file_api_chat_v1_chat_messages_proto_init() {
	if File_api_chat_v1_chat_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_chat_messages_proto_rawDesc), len(file_api_chat_v1_chat_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_chat_v1_chat_messages_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_chat_messages_proto_depIdxs,
		MessageInfos:      file_api_chat_v1_chat_messages_proto_msgTypes,
	}.Build()
	File_api_chat_v1_chat_messages_proto = out.File
	file_api_chat_v1_chat_messages_proto_goTypes = nil
	file_api_chat_v1_chat_messages_proto_depIdxs = nil
}
