// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	chatmodels "chat/internal/app/usecases/chat/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "chat/internal/app/models"

	types "chat/internal/app/models/types"
)

// ChatRepository is an autogenerated mock type for the ChatRepository type
type ChatRepository struct {
	mock.Mock
}

type ChatRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ChatRepository) EXPECT() *ChatRepository_Expecter {
	return &ChatRepository_Expecter{mock: &_m.Mock}
}

// CreateDirectChat provides a mock function with given fields: ctx, userID, participantID
func (_m *ChatRepository) CreateDirectChat(ctx context.Context, userID types.UserID, participantID types.UserID) (*models.Chat, error) {
	ret := _m.Called(ctx, userID, participantID)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirectChat")
	}

	var r0 *models.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID, types.UserID) (*models.Chat, error)); ok {
		return rf(ctx, userID, participantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID, types.UserID) *models.Chat); ok {
		r0 = rf(ctx, userID, participantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.UserID, types.UserID) error); ok {
		r1 = rf(ctx, userID, participantID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChatRepository_CreateDirectChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDirectChat'
type ChatRepository_CreateDirectChat_Call struct {
	*mock.Call
}

// CreateDirectChat is a helper method to define mock.On call
//   - ctx context.Context
//   - userID types.UserID
//   - participantID types.UserID
func (_e *ChatRepository_Expecter) CreateDirectChat(ctx interface{}, userID interface{}, participantID interface{}) *ChatRepository_CreateDirectChat_Call {
	return &ChatRepository_CreateDirectChat_Call{Call: _e.mock.On("CreateDirectChat", ctx, userID, participantID)}
}

func (_c *ChatRepository_CreateDirectChat_Call) Run(run func(ctx context.Context, userID types.UserID, participantID types.UserID)) *ChatRepository_CreateDirectChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.UserID), args[2].(types.UserID))
	})
	return _c
}

func (_c *ChatRepository_CreateDirectChat_Call) Return(_a0 *models.Chat, _a1 error) *ChatRepository_CreateDirectChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChatRepository_CreateDirectChat_Call) RunAndReturn(run func(context.Context, types.UserID, types.UserID) (*models.Chat, error)) *ChatRepository_CreateDirectChat_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessage provides a mock function with given fields: ctx, msg
func (_m *ChatRepository) CreateMessage(ctx context.Context, msg *models.Message) (*models.Message, error) {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 *models.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Message) (*models.Message, error)); ok {
		return rf(ctx, msg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Message) *models.Message); ok {
		r0 = rf(ctx, msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Message) error); ok {
		r1 = rf(ctx, msg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChatRepository_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type ChatRepository_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *models.Message
func (_e *ChatRepository_Expecter) CreateMessage(ctx interface{}, msg interface{}) *ChatRepository_CreateMessage_Call {
	return &ChatRepository_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, msg)}
}

func (_c *ChatRepository_CreateMessage_Call) Run(run func(ctx context.Context, msg *models.Message)) *ChatRepository_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Message))
	})
	return _c
}

func (_c *ChatRepository_CreateMessage_Call) Return(_a0 *models.Message, _a1 error) *ChatRepository_CreateMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChatRepository_CreateMessage_Call) RunAndReturn(run func(context.Context, *models.Message) (*models.Message, error)) *ChatRepository_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetChat provides a mock function with given fields: ctx, chatID
func (_m *ChatRepository) GetChat(ctx context.Context, chatID types.ChatID) (*models.Chat, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for GetChat")
	}

	var r0 *models.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatID) (*models.Chat, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatID) *models.Chat); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ChatID) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChatRepository_GetChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChat'
type ChatRepository_GetChat_Call struct {
	*mock.Call
}

// GetChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID types.ChatID
func (_e *ChatRepository_Expecter) GetChat(ctx interface{}, chatID interface{}) *ChatRepository_GetChat_Call {
	return &ChatRepository_GetChat_Call{Call: _e.mock.On("GetChat", ctx, chatID)}
}

func (_c *ChatRepository_GetChat_Call) Run(run func(ctx context.Context, chatID types.ChatID)) *ChatRepository_GetChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ChatID))
	})
	return _c
}

func (_c *ChatRepository_GetChat_Call) Return(_a0 *models.Chat, _a1 error) *ChatRepository_GetChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChatRepository_GetChat_Call) RunAndReturn(run func(context.Context, types.ChatID) (*models.Chat, error)) *ChatRepository_GetChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function with given fields: ctx, chatID, opts
func (_m *ChatRepository) GetMessages(ctx context.Context, chatID types.ChatID, opts ...chatmodels.GetMessagesOption) (*chatmodels.GetMessagesResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, chatID)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 *chatmodels.GetMessagesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatID, ...chatmodels.GetMessagesOption) (*chatmodels.GetMessagesResult, error)); ok {
		return rf(ctx, chatID, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatID, ...chatmodels.GetMessagesOption) *chatmodels.GetMessagesResult); ok {
		r0 = rf(ctx, chatID, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chatmodels.GetMessagesResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ChatID, ...chatmodels.GetMessagesOption) error); ok {
		r1 = rf(ctx, chatID, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChatRepository_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type ChatRepository_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID types.ChatID
//   - opts ...chatmodels.GetMessagesOption
func (_e *ChatRepository_Expecter) GetMessages(ctx interface{}, chatID interface{}, opts ...interface{}) *ChatRepository_GetMessages_Call {
	return &ChatRepository_GetMessages_Call{Call: _e.mock.On("GetMessages",
		append([]interface{}{ctx, chatID}, opts...)...)}
}

func (_c *ChatRepository_GetMessages_Call) Run(run func(ctx context.Context, chatID types.ChatID, opts ...chatmodels.GetMessagesOption)) *ChatRepository_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]chatmodels.GetMessagesOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(chatmodels.GetMessagesOption)
			}
		}
		run(args[0].(context.Context), args[1].(types.ChatID), variadicArgs...)
	})
	return _c
}

func (_c *ChatRepository_GetMessages_Call) Return(_a0 *chatmodels.GetMessagesResult, _a1 error) *ChatRepository_GetMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChatRepository_GetMessages_Call) RunAndReturn(run func(context.Context, types.ChatID, ...chatmodels.GetMessagesOption) (*chatmodels.GetMessagesResult, error)) *ChatRepository_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserChats provides a mock function with given fields: ctx, userID
func (_m *ChatRepository) GetUserChats(ctx context.Context, userID types.UserID) ([]*models.Chat, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserChats")
	}

	var r0 []*models.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) ([]*models.Chat, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) []*models.Chat); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChatRepository_GetUserChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserChats'
type ChatRepository_GetUserChats_Call struct {
	*mock.Call
}

// GetUserChats is a helper method to define mock.On call
//   - ctx context.Context
//   - userID types.UserID
func (_e *ChatRepository_Expecter) GetUserChats(ctx interface{}, userID interface{}) *ChatRepository_GetUserChats_Call {
	return &ChatRepository_GetUserChats_Call{Call: _e.mock.On("GetUserChats", ctx, userID)}
}

func (_c *ChatRepository_GetUserChats_Call) Run(run func(ctx context.Context, userID types.UserID)) *ChatRepository_GetUserChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.UserID))
	})
	return _c
}

func (_c *ChatRepository_GetUserChats_Call) Return(_a0 []*models.Chat, _a1 error) *ChatRepository_GetUserChats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChatRepository_GetUserChats_Call) RunAndReturn(run func(context.Context, types.UserID) ([]*models.Chat, error)) *ChatRepository_GetUserChats_Call {
	_c.Call.Return(run)
	return _c
}

// StreamMessages provides a mock function with given fields: ctx, chatID
func (_m *ChatRepository) StreamMessages(ctx context.Context, chatID types.ChatID) (<-chan *models.Message, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for StreamMessages")
	}

	var r0 <-chan *models.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatID) (<-chan *models.Message, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.ChatID) <-chan *models.Message); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *models.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.ChatID) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChatRepository_StreamMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamMessages'
type ChatRepository_StreamMessages_Call struct {
	*mock.Call
}

// StreamMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID types.ChatID
func (_e *ChatRepository_Expecter) StreamMessages(ctx interface{}, chatID interface{}) *ChatRepository_StreamMessages_Call {
	return &ChatRepository_StreamMessages_Call{Call: _e.mock.On("StreamMessages", ctx, chatID)}
}

func (_c *ChatRepository_StreamMessages_Call) Run(run func(ctx context.Context, chatID types.ChatID)) *ChatRepository_StreamMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ChatID))
	})
	return _c
}

func (_c *ChatRepository_StreamMessages_Call) Return(_a0 <-chan *models.Message, _a1 error) *ChatRepository_StreamMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ChatRepository_StreamMessages_Call) RunAndReturn(run func(context.Context, types.ChatID) (<-chan *models.Message, error)) *ChatRepository_StreamMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewChatRepository creates a new instance of ChatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatRepository {
	mock := &ChatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
