// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserIDProvider is an autogenerated mock type for the UserIDProvider type
type UserIDProvider struct {
	mock.Mock
}

type UserIDProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *UserIDProvider) EXPECT() *UserIDProvider_Expecter {
	return &UserIDProvider_Expecter{mock: &_m.Mock}
}

// GetUserIDFromIncomingContext provides a mock function with given fields: ctx
func (_m *UserIDProvider) GetUserIDFromIncomingContext(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUserIDFromIncomingContext")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserIDProvider_GetUserIDFromIncomingContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserIDFromIncomingContext'
type UserIDProvider_GetUserIDFromIncomingContext_Call struct {
	*mock.Call
}

// GetUserIDFromIncomingContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserIDProvider_Expecter) GetUserIDFromIncomingContext(ctx interface{}) *UserIDProvider_GetUserIDFromIncomingContext_Call {
	return &UserIDProvider_GetUserIDFromIncomingContext_Call{Call: _e.mock.On("GetUserIDFromIncomingContext", ctx)}
}

func (_c *UserIDProvider_GetUserIDFromIncomingContext_Call) Run(run func(ctx context.Context)) *UserIDProvider_GetUserIDFromIncomingContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserIDProvider_GetUserIDFromIncomingContext_Call) Return(_a0 string, _a1 error) *UserIDProvider_GetUserIDFromIncomingContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserIDProvider_GetUserIDFromIncomingContext_Call) RunAndReturn(run func(context.Context) (string, error)) *UserIDProvider_GetUserIDFromIncomingContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserIDProvider creates a new instance of UserIDProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserIDProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserIDProvider {
	mock := &UserIDProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
