// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "social/internal/app/models"

	mock "github.com/stretchr/testify/mock"

	socialmodels "social/internal/app/usecases/social/models"

	types "social/internal/app/models/types"
)

// SocialRepository is an autogenerated mock type for the SocialRepository type
type SocialRepository struct {
	mock.Mock
}

type SocialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SocialRepository) EXPECT() *SocialRepository_Expecter {
	return &SocialRepository_Expecter{mock: &_m.Mock}
}

// CreateFriendRequest provides a mock function with given fields: ctx, request
func (_m *SocialRepository) CreateFriendRequest(ctx context.Context, request *models.FriendRequest) (*models.FriendRequest, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateFriendRequest")
	}

	var r0 *models.FriendRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.FriendRequest) (*models.FriendRequest, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.FriendRequest) *models.FriendRequest); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FriendRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.FriendRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SocialRepository_CreateFriendRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFriendRequest'
type SocialRepository_CreateFriendRequest_Call struct {
	*mock.Call
}

// CreateFriendRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - request *models.FriendRequest
func (_e *SocialRepository_Expecter) CreateFriendRequest(ctx interface{}, request interface{}) *SocialRepository_CreateFriendRequest_Call {
	return &SocialRepository_CreateFriendRequest_Call{Call: _e.mock.On("CreateFriendRequest", ctx, request)}
}

func (_c *SocialRepository_CreateFriendRequest_Call) Run(run func(ctx context.Context, request *models.FriendRequest)) *SocialRepository_CreateFriendRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.FriendRequest))
	})
	return _c
}

func (_c *SocialRepository_CreateFriendRequest_Call) Return(_a0 *models.FriendRequest, _a1 error) *SocialRepository_CreateFriendRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SocialRepository_CreateFriendRequest_Call) RunAndReturn(run func(context.Context, *models.FriendRequest) (*models.FriendRequest, error)) *SocialRepository_CreateFriendRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetFriendRequests provides a mock function with given fields: ctx, selector
func (_m *SocialRepository) GetFriendRequests(ctx context.Context, selector socialmodels.FriendRequestSelector) ([]*models.FriendRequest, error) {
	ret := _m.Called(ctx, selector)

	if len(ret) == 0 {
		panic("no return value specified for GetFriendRequests")
	}

	var r0 []*models.FriendRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, socialmodels.FriendRequestSelector) ([]*models.FriendRequest, error)); ok {
		return rf(ctx, selector)
	}
	if rf, ok := ret.Get(0).(func(context.Context, socialmodels.FriendRequestSelector) []*models.FriendRequest); ok {
		r0 = rf(ctx, selector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FriendRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, socialmodels.FriendRequestSelector) error); ok {
		r1 = rf(ctx, selector)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SocialRepository_GetFriendRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFriendRequests'
type SocialRepository_GetFriendRequests_Call struct {
	*mock.Call
}

// GetFriendRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - selector socialmodels.FriendRequestSelector
func (_e *SocialRepository_Expecter) GetFriendRequests(ctx interface{}, selector interface{}) *SocialRepository_GetFriendRequests_Call {
	return &SocialRepository_GetFriendRequests_Call{Call: _e.mock.On("GetFriendRequests", ctx, selector)}
}

func (_c *SocialRepository_GetFriendRequests_Call) Run(run func(ctx context.Context, selector socialmodels.FriendRequestSelector)) *SocialRepository_GetFriendRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(socialmodels.FriendRequestSelector))
	})
	return _c
}

func (_c *SocialRepository_GetFriendRequests_Call) Return(_a0 []*models.FriendRequest, _a1 error) *SocialRepository_GetFriendRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SocialRepository_GetFriendRequests_Call) RunAndReturn(run func(context.Context, socialmodels.FriendRequestSelector) ([]*models.FriendRequest, error)) *SocialRepository_GetFriendRequests_Call {
	_c.Call.Return(run)
	return _c
}

// ListFriends provides a mock function with given fields: ctx, id, opts
func (_m *SocialRepository) ListFriends(ctx context.Context, id types.UserID, opts ...socialmodels.ListFriendsOption) (*socialmodels.ListFriendsResult, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListFriends")
	}

	var r0 *socialmodels.ListFriendsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID, ...socialmodels.ListFriendsOption) (*socialmodels.ListFriendsResult, error)); ok {
		return rf(ctx, id, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID, ...socialmodels.ListFriendsOption) *socialmodels.ListFriendsResult); ok {
		r0 = rf(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*socialmodels.ListFriendsResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.UserID, ...socialmodels.ListFriendsOption) error); ok {
		r1 = rf(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SocialRepository_ListFriends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFriends'
type SocialRepository_ListFriends_Call struct {
	*mock.Call
}

// ListFriends is a helper method to define mock.On call
//   - ctx context.Context
//   - id types.UserID
//   - opts ...socialmodels.ListFriendsOption
func (_e *SocialRepository_Expecter) ListFriends(ctx interface{}, id interface{}, opts ...interface{}) *SocialRepository_ListFriends_Call {
	return &SocialRepository_ListFriends_Call{Call: _e.mock.On("ListFriends",
		append([]interface{}{ctx, id}, opts...)...)}
}

func (_c *SocialRepository_ListFriends_Call) Run(run func(ctx context.Context, id types.UserID, opts ...socialmodels.ListFriendsOption)) *SocialRepository_ListFriends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]socialmodels.ListFriendsOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(socialmodels.ListFriendsOption)
			}
		}
		run(args[0].(context.Context), args[1].(types.UserID), variadicArgs...)
	})
	return _c
}

func (_c *SocialRepository_ListFriends_Call) Return(_a0 *socialmodels.ListFriendsResult, _a1 error) *SocialRepository_ListFriends_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SocialRepository_ListFriends_Call) RunAndReturn(run func(context.Context, types.UserID, ...socialmodels.ListFriendsOption) (*socialmodels.ListFriendsResult, error)) *SocialRepository_ListFriends_Call {
	_c.Call.Return(run)
	return _c
}

// ListRequests provides a mock function with given fields: ctx, userID
func (_m *SocialRepository) ListRequests(ctx context.Context, userID types.UserID) ([]*models.FriendRequest, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListRequests")
	}

	var r0 []*models.FriendRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) ([]*models.FriendRequest, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID) []*models.FriendRequest); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.FriendRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SocialRepository_ListRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRequests'
type SocialRepository_ListRequests_Call struct {
	*mock.Call
}

// ListRequests is a helper method to define mock.On call
//   - ctx context.Context
//   - userID types.UserID
func (_e *SocialRepository_Expecter) ListRequests(ctx interface{}, userID interface{}) *SocialRepository_ListRequests_Call {
	return &SocialRepository_ListRequests_Call{Call: _e.mock.On("ListRequests", ctx, userID)}
}

func (_c *SocialRepository_ListRequests_Call) Run(run func(ctx context.Context, userID types.UserID)) *SocialRepository_ListRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.UserID))
	})
	return _c
}

func (_c *SocialRepository_ListRequests_Call) Return(_a0 []*models.FriendRequest, _a1 error) *SocialRepository_ListRequests_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SocialRepository_ListRequests_Call) RunAndReturn(run func(context.Context, types.UserID) ([]*models.FriendRequest, error)) *SocialRepository_ListRequests_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFriend provides a mock function with given fields: ctx, userID, friendID
func (_m *SocialRepository) RemoveFriend(ctx context.Context, userID types.UserID, friendID types.UserID) error {
	ret := _m.Called(ctx, userID, friendID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFriend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, types.UserID, types.UserID) error); ok {
		r0 = rf(ctx, userID, friendID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SocialRepository_RemoveFriend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFriend'
type SocialRepository_RemoveFriend_Call struct {
	*mock.Call
}

// RemoveFriend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID types.UserID
//   - friendID types.UserID
func (_e *SocialRepository_Expecter) RemoveFriend(ctx interface{}, userID interface{}, friendID interface{}) *SocialRepository_RemoveFriend_Call {
	return &SocialRepository_RemoveFriend_Call{Call: _e.mock.On("RemoveFriend", ctx, userID, friendID)}
}

func (_c *SocialRepository_RemoveFriend_Call) Run(run func(ctx context.Context, userID types.UserID, friendID types.UserID)) *SocialRepository_RemoveFriend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.UserID), args[2].(types.UserID))
	})
	return _c
}

func (_c *SocialRepository_RemoveFriend_Call) Return(_a0 error) *SocialRepository_RemoveFriend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SocialRepository_RemoveFriend_Call) RunAndReturn(run func(context.Context, types.UserID, types.UserID) error) *SocialRepository_RemoveFriend_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFriendRequestStatus provides a mock function with given fields: ctx, id, status
func (_m *SocialRepository) UpdateFriendRequestStatus(ctx context.Context, id types.RequestID, status models.FriendRequestStatus) (*models.FriendRequest, error) {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFriendRequestStatus")
	}

	var r0 *models.FriendRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestID, models.FriendRequestStatus) (*models.FriendRequest, error)); ok {
		return rf(ctx, id, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, types.RequestID, models.FriendRequestStatus) *models.FriendRequest); ok {
		r0 = rf(ctx, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FriendRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, types.RequestID, models.FriendRequestStatus) error); ok {
		r1 = rf(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SocialRepository_UpdateFriendRequestStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFriendRequestStatus'
type SocialRepository_UpdateFriendRequestStatus_Call struct {
	*mock.Call
}

// UpdateFriendRequestStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id types.RequestID
//   - status models.FriendRequestStatus
func (_e *SocialRepository_Expecter) UpdateFriendRequestStatus(ctx interface{}, id interface{}, status interface{}) *SocialRepository_UpdateFriendRequestStatus_Call {
	return &SocialRepository_UpdateFriendRequestStatus_Call{Call: _e.mock.On("UpdateFriendRequestStatus", ctx, id, status)}
}

func (_c *SocialRepository_UpdateFriendRequestStatus_Call) Run(run func(ctx context.Context, id types.RequestID, status models.FriendRequestStatus)) *SocialRepository_UpdateFriendRequestStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.RequestID), args[2].(models.FriendRequestStatus))
	})
	return _c
}

func (_c *SocialRepository_UpdateFriendRequestStatus_Call) Return(_a0 *models.FriendRequest, _a1 error) *SocialRepository_UpdateFriendRequestStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SocialRepository_UpdateFriendRequestStatus_Call) RunAndReturn(run func(context.Context, types.RequestID, models.FriendRequestStatus) (*models.FriendRequest, error)) *SocialRepository_UpdateFriendRequestStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewSocialRepository creates a new instance of SocialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSocialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SocialRepository {
	mock := &SocialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
