// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TransactionManager is an autogenerated mock type for the TransactionManager type
type TransactionManager struct {
	mock.Mock
}

type TransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *TransactionManager) EXPECT() *TransactionManager_Expecter {
	return &TransactionManager_Expecter{mock: &_m.Mock}
}

// RunReadCommitted provides a mock function with given fields: ctx, f
func (_m *TransactionManager) RunReadCommitted(ctx context.Context, f func(context.Context) error) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for RunReadCommitted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionManager_RunReadCommitted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunReadCommitted'
type TransactionManager_RunReadCommitted_Call struct {
	*mock.Call
}

// RunReadCommitted is a helper method to define mock.On call
//   - ctx context.Context
//   - f func(context.Context) error
func (_e *TransactionManager_Expecter) RunReadCommitted(ctx interface{}, f interface{}) *TransactionManager_RunReadCommitted_Call {
	return &TransactionManager_RunReadCommitted_Call{Call: _e.mock.On("RunReadCommitted", ctx, f)}
}

func (_c *TransactionManager_RunReadCommitted_Call) Run(run func(ctx context.Context, f func(context.Context) error)) *TransactionManager_RunReadCommitted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *TransactionManager_RunReadCommitted_Call) Return(_a0 error) *TransactionManager_RunReadCommitted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TransactionManager_RunReadCommitted_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *TransactionManager_RunReadCommitted_Call {
	_c.Call.Return(run)
	return _c
}

// NewTransactionManager creates a new instance of TransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionManager {
	mock := &TransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
