// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/bufbuild/protovalidate-go"
	"google.golang.org/grpc"
	context2 "lib/auth/context"
	middleware_grpc2 "lib/middleware/grpc"
	social3 "social/internal/app/controllers/social"
	"social/internal/app/repositories/social"
	"social/internal/app/server"
	social2 "social/internal/app/usecases/social"
	"social/internal/middleware/grpc"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*server.Server, error) {
	validator, err := newValidator()
	if err != nil {
		return nil, err
	}
	v := newMiddlewares(validator)
	config := newConfig(v)
	repository := social.NewRepository()
	userIDProvider := newUserIDProvider()
	deps := social2.Deps{
		SocialRepository: repository,
		UserIDProvider:   userIDProvider,
	}
	usecase := social2.NewUsecase(deps)
	socialDeps := social3.Deps{
		SocialUsecase: usecase,
	}
	controller := social3.New(socialDeps)
	contollers := server.Contollers{
		SocialServiceServer: controller,
	}
	serverServer, err := server.New(ctx, config, contollers)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}

// wire.go:

const address = ":8080"

func newValidator() (*protovalidate.Validator, error) {
	return protovalidate.New(protovalidate.WithDisableLazy(false))
}

func newMiddlewares(validator *protovalidate.Validator) []grpc.UnaryServerInterceptor {
	return []grpc.UnaryServerInterceptor{middleware_grpc.ErrorsUnaryServerInterceptor(), middleware_grpc2.ValidateUnaryServerInterceptor(validator)}
}

func newConfig(mws []grpc.UnaryServerInterceptor) server.Config {
	return server.Config{
		GRPCPort:               address,
		ChainUnaryInterceptors: mws,
	}
}

func newUserIDProvider() social2.UserIDProvider {
	return context2.MyUserIDProvider{}
}
