// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/auth/v1/auth_messages.proto

package auth

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest - Запрос на регистрацию
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Почта
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Пароль
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_messages_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegisterResponse - Ответ RegisterRequest
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя
	UserId        string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_messages_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// LoginRequest - Запрос на вход
type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Почта
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Пароль
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_messages_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse - Ответ LoginRequest
type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access токен
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	// Refresh токен
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	// Id пользователя
	UserId        string `protobuf:"bytes,3,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_messages_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// RefreshRequest - Запрос RefreshToken
type RefreshRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Refresh токен
	RefreshToken  string `protobuf:"bytes,1,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_messages_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// RefreshResponse - Ответ RefreshToken
type RefreshResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Access токен
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,proto3" json:"access_token,omitempty"`
	// Refresh токен
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	// Id пользователя
	UserId        string `protobuf:"bytes,3,opt,name=user_id,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_v1_auth_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_v1_auth_messages_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_api_auth_v1_auth_messages_proto protoreflect.FileDescriptor

const file_api_auth_v1_auth_messages_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/auth/v1/auth_messages.proto\x12\vapi.auth.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x99\x02\n" +
	"\x0fRegisterRequest\x12`\n" +
	"\x05email\x18\x01 \x01(\tBJ\x92A=*\x05email2\x1eemail пользователяJ\x10\"user@gmail.com\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02`\x01R\x05email\x12O\n" +
	"\bpassword\x18\x02 \x01(\tB3\x92A&*\bpassword2\fпарольJ\b\"xQta78\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\bpassword:S\x92AP\n" +
	"N*\x0fRegisterRequest2(Запрос на регистрацию\xd2\x01\x05email\xd2\x01\bpassword\"\xc4\x01\n" +
	"\x10RegisterResponse\x12o\n" +
	"\auser_id\x18\x01 \x01(\tBU\x92AR*\auser_id2\x1bId пользователяJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\aR\auser_id:?\x92A<\n" +
	":*\x10RegisterResponse2&RegisterResponse - ответ Register\"\x85\x02\n" +
	"\fLoginRequest\x12`\n" +
	"\x05email\x18\x01 \x01(\tBJ\x92A=*\x05email2\x1eemail пользователяJ\x10\"user@gmail.com\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02`\x01R\x05email\x12O\n" +
	"\bpassword\x18\x02 \x01(\tB3\x92A&*\bpassword2\fпарольJ\b\"xQta78\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\bpassword:B\x92A?\n" +
	"=*\fLoginRequest2\x1aЗапрос на вход\xd2\x01\x05email\xd2\x01\bpassword\"\xae\x03\n" +
	"\rLoginResponse\x12w\n" +
	"\faccess_token\x18\x01 \x01(\tBS\x92AP*\faccess_token2\x11Access токенJ)\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\"\x9a\x02\x01\aR\faccess_token\x12{\n" +
	"\rrefresh_token\x18\x02 \x01(\tBU\x92AR*\rrefresh_token2\x12Refresh токенJ)\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\"\x9a\x02\x01\aR\rrefresh_token\x12o\n" +
	"\auser_id\x18\x03 \x01(\tBU\x92AR*\auser_id2\x1bId пользователяJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\aR\auser_id:6\x92A3\n" +
	"1*\rLoginResponse2 LoginResponse - ответ Login\"\xdf\x01\n" +
	"\x0eRefreshRequest\x12\x85\x01\n" +
	"\rrefresh_token\x18\x01 \x01(\tB_\x92AR*\rrefresh_token2\x12Refresh токенJ)\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\rrefresh_token:E\x92AB\n" +
	"@*\x13RefreshTokenRequest2\x19Запрос RefreshToken\xd2\x01\rrefresh_token\"\xb6\x03\n" +
	"\x0fRefreshResponse\x12w\n" +
	"\faccess_token\x18\x01 \x01(\tBS\x92AP*\faccess_token2\x11Access токенJ)\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\"\x9a\x02\x01\aR\faccess_token\x12{\n" +
	"\rrefresh_token\x18\x02 \x01(\tBU\x92AR*\rrefresh_token2\x12Refresh токенJ)\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...\"\x9a\x02\x01\aR\rrefresh_token\x12o\n" +
	"\auser_id\x18\x03 \x01(\tBU\x92AR*\auser_id2\x1bId пользователяJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\aR\auser_id:<\x92A9\n" +
	"7*\x0fRefreshResponse2$RefreshResponse - ответ RefreshB\x8d\x01\n" +
	"\x0fcom.api.auth.v1B\x11AuthMessagesProtoP\x01Z\x19auth/pkg/api/auth/v1;auth\xa2\x02\x03AAX\xaa\x02\vApi.Auth.V1\xca\x02\vApi\\Auth\\V1\xe2\x02\x17Api\\Auth\\V1\\GPBMetadata\xea\x02\rApi::Auth::V1b\x06proto3"

var (
	file_api_auth_v1_auth_messages_proto_rawDescOnce sync.Once
	file_api_auth_v1_auth_messages_proto_rawDescData []byte
)

func file_api_auth_v1_auth_messages_proto_rawDescGZIP() []byte {
	file_api_auth_v1_auth_messages_proto_rawDescOnce.Do(func() {
		file_api_auth_v1_auth_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_v1_auth_messages_proto_rawDesc), len(file_api_auth_v1_auth_messages_proto_rawDesc)))
	})
	return file_api_auth_v1_auth_messages_proto_rawDescData
}

var file_api_auth_v1_auth_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_auth_v1_auth_messages_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: api.auth.v1.RegisterRequest
	(*RegisterResponse)(nil), // 1: api.auth.v1.RegisterResponse
	(*LoginRequest)(nil),     // 2: api.auth.v1.LoginRequest
	(*LoginResponse)(nil),    // 3: api.auth.v1.LoginResponse
	(*RefreshRequest)(nil),   // 4: api.auth.v1.RefreshRequest
	(*RefreshResponse)(nil),  // 5: api.auth.v1.RefreshResponse
}
var file_api_auth_v1_auth_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_auth_messages_proto_init() }
func file_api_auth_v1_auth_messages_proto_init() {
	if File_api_auth_v1_auth_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_auth_messages_proto_rawDesc), len(file_api_auth_v1_auth_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_auth_v1_auth_messages_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_auth_messages_proto_depIdxs,
		MessageInfos:      file_api_auth_v1_auth_messages_proto_msgTypes,
	}.Build()
	File_api_auth_v1_auth_messages_proto = out.File
	file_api_auth_v1_auth_messages_proto_goTypes = nil
	file_api_auth_v1_auth_messages_proto_depIdxs = nil
}
