// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/auth/v1/auth_service.proto

package auth

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_auth_v1_auth_service_proto protoreflect.FileDescriptor

const file_api_auth_v1_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/auth/v1/auth_service.proto\x12\vapi.auth.v1\x1a\x1fapi/auth/v1/auth_messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xa3\x02\n" +
	"\vAuthService\x12`\n" +
	"\bRegister\x12\x1c.api.auth.v1.RegisterRequest\x1a\x1d.api.auth.v1.RegisterResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/register\x12T\n" +
	"\x05Login\x12\x19.api.auth.v1.LoginRequest\x1a\x1a.api.auth.v1.LoginResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12\\\n" +
	"\aRefresh\x12\x1b.api.auth.v1.RefreshRequest\x1a\x1c.api.auth.v1.RefreshResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/refreshB\xcd\x01\x92A>\x12\x14\n" +
	"\vAuthService2\x050.0.1*\x02\x01\x022\x10application/json:\x10application/json\n" +
	"\x0fcom.api.auth.v1B\x10AuthServiceProtoP\x01Z\x19auth/pkg/api/auth/v1;auth\xa2\x02\x03AAX\xaa\x02\vApi.Auth.V1\xca\x02\vApi\\Auth\\V1\xe2\x02\x17Api\\Auth\\V1\\GPBMetadata\xea\x02\rApi::Auth::V1b\x06proto3"

var file_api_auth_v1_auth_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: api.auth.v1.RegisterRequest
	(*LoginRequest)(nil),     // 1: api.auth.v1.LoginRequest
	(*RefreshRequest)(nil),   // 2: api.auth.v1.RefreshRequest
	(*RegisterResponse)(nil), // 3: api.auth.v1.RegisterResponse
	(*LoginResponse)(nil),    // 4: api.auth.v1.LoginResponse
	(*RefreshResponse)(nil),  // 5: api.auth.v1.RefreshResponse
}
var file_api_auth_v1_auth_service_proto_depIdxs = []int32{
	0, // 0: api.auth.v1.AuthService.Register:input_type -> api.auth.v1.RegisterRequest
	1, // 1: api.auth.v1.AuthService.Login:input_type -> api.auth.v1.LoginRequest
	2, // 2: api.auth.v1.AuthService.Refresh:input_type -> api.auth.v1.RefreshRequest
	3, // 3: api.auth.v1.AuthService.Register:output_type -> api.auth.v1.RegisterResponse
	4, // 4: api.auth.v1.AuthService.Login:output_type -> api.auth.v1.LoginResponse
	5, // 5: api.auth.v1.AuthService.Refresh:output_type -> api.auth.v1.RefreshResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_auth_v1_auth_service_proto_init() }
func file_api_auth_v1_auth_service_proto_init() {
	if File_api_auth_v1_auth_service_proto != nil {
		return
	}
	file_api_auth_v1_auth_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_v1_auth_service_proto_rawDesc), len(file_api_auth_v1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_api_auth_v1_auth_service_proto_depIdxs,
	}.Build()
	File_api_auth_v1_auth_service_proto = out.File
	file_api_auth_v1_auth_service_proto_goTypes = nil
	file_api_auth_v1_auth_service_proto_depIdxs = nil
}
