// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/users/v1/users_messages.proto

package user

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateProfileRequest - запрос на создание профиля
type CreateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя
	UserId string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	// Никнейм
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Биография
	Bio string `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	// URL аватара
	AvatarUrl     string `protobuf:"bytes,4,opt,name=avatar_url,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileRequest) Reset() {
	*x = CreateProfileRequest{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileRequest) ProtoMessage() {}

func (x *CreateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileRequest.ProtoReflect.Descriptor instead.
func (*CreateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CreateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// CreateProfileResponse - ответ на создание профиля
type CreateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Созданный профиль
	Profile       *UserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProfileResponse) Reset() {
	*x = CreateProfileResponse{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProfileResponse) ProtoMessage() {}

func (x *CreateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProfileResponse.ProtoReflect.Descriptor instead.
func (*CreateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// UpdateProfileRequest - запрос на обновление профиля
type UpdateProfileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя
	UserId string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	// Никнейм
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Биография
	Bio string `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	// URL аватара
	AvatarUrl     string `protobuf:"bytes,4,opt,name=avatar_url,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

// UpdateProfileResponse - ответ на обновление профиля
type UpdateProfileResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Обновлённый профиль
	Profile       *UserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// GetProfileByIDRequest - запрос на получение профиля по ID
type GetProfileByIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDRequest) Reset() {
	*x = GetProfileByIDRequest{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDRequest) ProtoMessage() {}

func (x *GetProfileByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GetProfileByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetProfileByIDResponse - ответ на получение профиля по ID
type GetProfileByIDResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Профиль пользователя
	Profile       *UserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByIDResponse) Reset() {
	*x = GetProfileByIDResponse{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByIDResponse) ProtoMessage() {}

func (x *GetProfileByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByIDResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByIDResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GetProfileByIDResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// GetProfileByNicknameRequest - запрос на получение профиля по никнейму
type GetProfileByNicknameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Никнейм
	Nickname      string `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByNicknameRequest) Reset() {
	*x = GetProfileByNicknameRequest{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByNicknameRequest) ProtoMessage() {}

func (x *GetProfileByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByNicknameRequest.ProtoReflect.Descriptor instead.
func (*GetProfileByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GetProfileByNicknameRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// GetProfileByNicknameResponse - ответ на получение профиля по никнейму
type GetProfileByNicknameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Профиль пользователя
	Profile       *UserProfile `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileByNicknameResponse) Reset() {
	*x = GetProfileByNicknameResponse{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileByNicknameResponse) ProtoMessage() {}

func (x *GetProfileByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileByNicknameResponse.ProtoReflect.Descriptor instead.
func (*GetProfileByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GetProfileByNicknameResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

// SearchByNicknameRequest - запрос поиска пользователей по никнейму
type SearchByNicknameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Поисковый запрос
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Лимит количества результатов
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByNicknameRequest) Reset() {
	*x = SearchByNicknameRequest{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByNicknameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByNicknameRequest) ProtoMessage() {}

func (x *SearchByNicknameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByNicknameRequest.ProtoReflect.Descriptor instead.
func (*SearchByNicknameRequest) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{8}
}

func (x *SearchByNicknameRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchByNicknameRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// SearchByNicknameResponse - ответ поиска пользователей по никнейму
type SearchByNicknameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Список найденных профилей
	Results       []*UserProfile `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchByNicknameResponse) Reset() {
	*x = SearchByNicknameResponse{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchByNicknameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchByNicknameResponse) ProtoMessage() {}

func (x *SearchByNicknameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchByNicknameResponse.ProtoReflect.Descriptor instead.
func (*SearchByNicknameResponse) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{9}
}

func (x *SearchByNicknameResponse) GetResults() []*UserProfile {
	if x != nil {
		return x.Results
	}
	return nil
}

// UserProfile - структура профиля пользователя
type UserProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id пользователя
	UserId string `protobuf:"bytes,1,opt,name=user_id,proto3" json:"user_id,omitempty"`
	// Никнейм
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Биография
	Bio string `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	// URL аватара
	AvatarUrl     string `protobuf:"bytes,4,opt,name=avatar_url,proto3" json:"avatar_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_api_users_v1_users_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_users_v1_users_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_api_users_v1_users_messages_proto_rawDescGZIP(), []int{10}
}

func (x *UserProfile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_api_users_v1_users_messages_proto protoreflect.FileDescriptor

const file_api_users_v1_users_messages_proto_rawDesc = "" +
	"\n" +
	"!api/users/v1/users_messages.proto\x12\fapi.users.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x8d\x05\n" +
	"\x14CreateProfileRequest\x12y\n" +
	"\auser_id\x18\x01 \x01(\tB_\x92AR*\auser_id2\x1bId пользователяJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\auser_id\x12}\n" +
	"\bnickname\x18\x02 \x01(\tBa\x92AC*\bnickname2'Никнейм пользователяJ\n" +
	"\"john_doe\"\x9a\x02\x01\a\xe0A\x02\xbaH\x15r\x132\x11^[a-z0-9_]{3,20}$R\bnickname\x12x\n" +
	"\x03bio\x18\x03 \x01(\tBf\x92Ac*\x03bio2+Биография пользователяJ+\"Люблю программировать\"\x9a\x02\x01\aR\x03bio\x12\x82\x01\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tBb\x92A_*\n" +
	"avatar_url2+URL аватара пользователяJ \"https://example.com/avatar.png\"\x9a\x02\x01\aR\n" +
	"avatar_url:|\x92Ay\n" +
	"w*\x14CreateProfileRequest2JЗапрос на создание профиля пользователя\xd2\x01\auser_id\xd2\x01\bnickname\"\xb4\x01\n" +
	"\x15CreateProfileResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.api.users.v1.UserProfileR\aprofile:f\x92Ac\n" +
	"a*\x15CreateProfileResponse2HОтвет на создание профиля пользователя\"\x83\x05\n" +
	"\x14UpdateProfileRequest\x12y\n" +
	"\auser_id\x18\x01 \x01(\tB_\x92AR*\auser_id2\x1bId пользователяJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\auser_id\x12z\n" +
	"\bnickname\x18\x02 \x01(\tB^\x92AC*\bnickname2'Никнейм пользователяJ\n" +
	"\"john_doe\"\x9a\x02\x01\a\xbaH\x15r\x132\x11^[a-z0-9_]{3,20}$R\bnickname\x12x\n" +
	"\x03bio\x18\x03 \x01(\tBf\x92Ac*\x03bio2+Биография пользователяJ+\"Люблю программировать\"\x9a\x02\x01\aR\x03bio\x12\x82\x01\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tBb\x92A_*\n" +
	"avatar_url2+URL аватара пользователяJ \"https://example.com/avatar.png\"\x9a\x02\x01\aR\n" +
	"avatar_url:u\x92Ar\n" +
	"p*\x14UpdateProfileRequest2NЗапрос на обновление профиля пользователя\xd2\x01\auser_id\"\xb8\x01\n" +
	"\x15UpdateProfileResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.api.users.v1.UserProfileR\aprofile:j\x92Ag\n" +
	"e*\x15UpdateProfileResponse2LОтвет на обновление профиля пользователя\"\xfc\x01\n" +
	"\x15GetProfileByIDRequest\x12j\n" +
	"\x02id\x18\x01 \x01(\tBZ\x92AM*\x02id2\x1bId пользователяJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\x02id:w\x92At\n" +
	"r*\x15GetProfileByIDRequest2TЗапрос на получение профиля пользователя по ID\xd2\x01\x02id\"\xc0\x01\n" +
	"\x16GetProfileByIDResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.api.users.v1.UserProfileR\aprofile:q\x92An\n" +
	"l*\x16GetProfileByIDResponse2RОтвет на получение профиля пользователя по ID\"\xa1\x02\n" +
	"\x1bGetProfileByNicknameRequest\x12l\n" +
	"\bnickname\x18\x01 \x01(\tBP\x92AC*\bnickname2'Никнейм пользователяJ\n" +
	"\"john_doe\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\bnickname:\x93\x01\x92A\x8f\x01\n" +
	"\x8c\x01*\x1bGetProfileByNicknameRequest2bЗапрос на получение профиля пользователя по никнейму\xd2\x01\bnickname\"\xdd\x01\n" +
	"\x1cGetProfileByNicknameResponse\x123\n" +
	"\aprofile\x18\x01 \x01(\v2\x19.api.users.v1.UserProfileR\aprofile:\x87\x01\x92A\x83\x01\n" +
	"\x80\x01*\x1cGetProfileByNicknameResponse2`Ответ на получение профиля пользователя по никнейму\"\xe3\x02\n" +
	"\x17SearchByNicknameRequest\x12o\n" +
	"\x05query\x18\x01 \x01(\tBY\x92AL*\x05query27Поисковый запрос для никнеймаJ\x06\"john\"\x9a\x02\x01\a\xe0A\x02\xbaH\x04r\x02\x10\x01R\x05query\x12`\n" +
	"\x05limit\x18\x02 \x01(\x05BJ\x92AG*\x05limit26Лимит количества результатовJ\x0220\x9a\x02\x01\x03R\x05limit:u\x92Ar\n" +
	"p*\x17SearchByNicknameRequest2MЗапрос на поиск пользователей по никнейму\xd2\x01\x05query\"\xbd\x01\n" +
	"\x18SearchByNicknameResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.api.users.v1.UserProfileR\aresults:l\x92Ai\n" +
	"g*\x18SearchByNicknameResponse2KОтвет на поиск пользователей по никнейму\"\xb1\x04\n" +
	"\vUserProfile\x12o\n" +
	"\auser_id\x18\x01 \x01(\tBU\x92AR*\auser_id2\x1bId пользователяJ&\"123e4567-e89b-12d3-a456-426614174000\"\x9a\x02\x01\aR\auser_id\x12b\n" +
	"\bnickname\x18\x02 \x01(\tBF\x92AC*\bnickname2'Никнейм пользователяJ\n" +
	"\"john_doe\"\x9a\x02\x01\aR\bnickname\x12x\n" +
	"\x03bio\x18\x03 \x01(\tBf\x92Ac*\x03bio2+Биография пользователяJ+\"Люблю программировать\"\x9a\x02\x01\aR\x03bio\x12\x82\x01\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tBb\x92A_*\n" +
	"avatar_url2+URL аватара пользователяJ \"https://example.com/avatar.png\"\x9a\x02\x01\aR\n" +
	"avatar_url:N\x92AK\n" +
	"I*\vUserProfile2:Структура профиля пользователяB\x95\x01\n" +
	"\x10com.api.users.v1B\x12UsersMessagesProtoP\x01Z\x1busers/pkg/api/users/v1;user\xa2\x02\x03AUX\xaa\x02\fApi.Users.V1\xca\x02\fApi\\Users\\V1\xe2\x02\x18Api\\Users\\V1\\GPBMetadata\xea\x02\x0eApi::Users::V1b\x06proto3"

var (
	file_api_users_v1_users_messages_proto_rawDescOnce sync.Once
	file_api_users_v1_users_messages_proto_rawDescData []byte
)

func file_api_users_v1_users_messages_proto_rawDescGZIP() []byte {
	file_api_users_v1_users_messages_proto_rawDescOnce.Do(func() {
		file_api_users_v1_users_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_users_v1_users_messages_proto_rawDesc), len(file_api_users_v1_users_messages_proto_rawDesc)))
	})
	return file_api_users_v1_users_messages_proto_rawDescData
}

var file_api_users_v1_users_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_users_v1_users_messages_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),         // 0: api.users.v1.CreateProfileRequest
	(*CreateProfileResponse)(nil),        // 1: api.users.v1.CreateProfileResponse
	(*UpdateProfileRequest)(nil),         // 2: api.users.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),        // 3: api.users.v1.UpdateProfileResponse
	(*GetProfileByIDRequest)(nil),        // 4: api.users.v1.GetProfileByIDRequest
	(*GetProfileByIDResponse)(nil),       // 5: api.users.v1.GetProfileByIDResponse
	(*GetProfileByNicknameRequest)(nil),  // 6: api.users.v1.GetProfileByNicknameRequest
	(*GetProfileByNicknameResponse)(nil), // 7: api.users.v1.GetProfileByNicknameResponse
	(*SearchByNicknameRequest)(nil),      // 8: api.users.v1.SearchByNicknameRequest
	(*SearchByNicknameResponse)(nil),     // 9: api.users.v1.SearchByNicknameResponse
	(*UserProfile)(nil),                  // 10: api.users.v1.UserProfile
}
var file_api_users_v1_users_messages_proto_depIdxs = []int32{
	10, // 0: api.users.v1.CreateProfileResponse.profile:type_name -> api.users.v1.UserProfile
	10, // 1: api.users.v1.UpdateProfileResponse.profile:type_name -> api.users.v1.UserProfile
	10, // 2: api.users.v1.GetProfileByIDResponse.profile:type_name -> api.users.v1.UserProfile
	10, // 3: api.users.v1.GetProfileByNicknameResponse.profile:type_name -> api.users.v1.UserProfile
	10, // 4: api.users.v1.SearchByNicknameResponse.results:type_name -> api.users.v1.UserProfile
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_users_v1_users_messages_proto_init() }
func file_api_users_v1_users_messages_proto_init() {
	if File_api_users_v1_users_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_users_messages_proto_rawDesc), len(file_api_users_v1_users_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_users_v1_users_messages_proto_goTypes,
		DependencyIndexes: file_api_users_v1_users_messages_proto_depIdxs,
		MessageInfos:      file_api_users_v1_users_messages_proto_msgTypes,
	}.Build()
	File_api_users_v1_users_messages_proto = out.File
	file_api_users_v1_users_messages_proto_goTypes = nil
	file_api_users_v1_users_messages_proto_depIdxs = nil
}
