// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/users/v1/users_service.proto

package user

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_users_v1_users_service_proto protoreflect.FileDescriptor

const file_api_users_v1_users_service_proto_rawDesc = "" +
	"\n" +
	" api/users/v1/users_service.proto\x12\fapi.users.v1\x1a!api/users/v1/users_messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x8d\x05\n" +
	"\vUserService\x12n\n" +
	"\rCreateProfile\x12\".api.users.v1.CreateProfileRequest\x1a#.api.users.v1.CreateProfileResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12\x84\x01\n" +
	"\rUpdateProfile\x12\".api.users.v1.UpdateProfileRequest\x1a#.api.users.v1.UpdateProfileResponse\"*\x82\xd3\xe4\x93\x02$:\rupdate_fields2\x13/v1/users/{user_id}\x12s\n" +
	"\x0eGetProfileByID\x12#.api.users.v1.GetProfileByIDRequest\x1a$.api.users.v1.GetProfileByIDResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/users/{id}\x12\x94\x01\n" +
	"\x14GetProfileByNickname\x12).api.users.v1.GetProfileByNicknameRequest\x1a*.api.users.v1.GetProfileByNicknameResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/users/nickname/{nickname}\x12{\n" +
	"\x10SearchByNickname\x12%.api.users.v1.SearchByNicknameRequest\x1a&.api.users.v1.SearchByNicknameResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/users/searchB\xd5\x01\x92A>\x12\x14\n" +
	"\vUserService2\x050.0.1*\x02\x01\x022\x10application/json:\x10application/json\n" +
	"\x10com.api.users.v1B\x11UsersServiceProtoP\x01Z\x1busers/pkg/api/users/v1;user\xa2\x02\x03AUX\xaa\x02\fApi.Users.V1\xca\x02\fApi\\Users\\V1\xe2\x02\x18Api\\Users\\V1\\GPBMetadata\xea\x02\x0eApi::Users::V1b\x06proto3"

var file_api_users_v1_users_service_proto_goTypes = []any{
	(*CreateProfileRequest)(nil),         // 0: api.users.v1.CreateProfileRequest
	(*UpdateProfileRequest)(nil),         // 1: api.users.v1.UpdateProfileRequest
	(*GetProfileByIDRequest)(nil),        // 2: api.users.v1.GetProfileByIDRequest
	(*GetProfileByNicknameRequest)(nil),  // 3: api.users.v1.GetProfileByNicknameRequest
	(*SearchByNicknameRequest)(nil),      // 4: api.users.v1.SearchByNicknameRequest
	(*CreateProfileResponse)(nil),        // 5: api.users.v1.CreateProfileResponse
	(*UpdateProfileResponse)(nil),        // 6: api.users.v1.UpdateProfileResponse
	(*GetProfileByIDResponse)(nil),       // 7: api.users.v1.GetProfileByIDResponse
	(*GetProfileByNicknameResponse)(nil), // 8: api.users.v1.GetProfileByNicknameResponse
	(*SearchByNicknameResponse)(nil),     // 9: api.users.v1.SearchByNicknameResponse
}
var file_api_users_v1_users_service_proto_depIdxs = []int32{
	0, // 0: api.users.v1.UserService.CreateProfile:input_type -> api.users.v1.CreateProfileRequest
	1, // 1: api.users.v1.UserService.UpdateProfile:input_type -> api.users.v1.UpdateProfileRequest
	2, // 2: api.users.v1.UserService.GetProfileByID:input_type -> api.users.v1.GetProfileByIDRequest
	3, // 3: api.users.v1.UserService.GetProfileByNickname:input_type -> api.users.v1.GetProfileByNicknameRequest
	4, // 4: api.users.v1.UserService.SearchByNickname:input_type -> api.users.v1.SearchByNicknameRequest
	5, // 5: api.users.v1.UserService.CreateProfile:output_type -> api.users.v1.CreateProfileResponse
	6, // 6: api.users.v1.UserService.UpdateProfile:output_type -> api.users.v1.UpdateProfileResponse
	7, // 7: api.users.v1.UserService.GetProfileByID:output_type -> api.users.v1.GetProfileByIDResponse
	8, // 8: api.users.v1.UserService.GetProfileByNickname:output_type -> api.users.v1.GetProfileByNicknameResponse
	9, // 9: api.users.v1.UserService.SearchByNickname:output_type -> api.users.v1.SearchByNicknameResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_users_v1_users_service_proto_init() }
func file_api_users_v1_users_service_proto_init() {
	if File_api_users_v1_users_service_proto != nil {
		return
	}
	file_api_users_v1_users_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_users_v1_users_service_proto_rawDesc), len(file_api_users_v1_users_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_users_v1_users_service_proto_goTypes,
		DependencyIndexes: file_api_users_v1_users_service_proto_depIdxs,
	}.Build()
	File_api_users_v1_users_service_proto = out.File
	file_api_users_v1_users_service_proto_goTypes = nil
	file_api_users_v1_users_service_proto_depIdxs = nil
}
